spring:
  datasource:
    url: jdbc:mysql://localhost:6603/mydb
    username: root
    password: DoNtTrY
  jpa:
    hibernate:
      ddl-auto: update

hibernate:
  dialect=org:
    hibernate:
      dialect: MySQL8Dialect